# Post request for signup
POST http://localhost:8080/api/signup
Content-Type: application/json

{
    "username": "gukkey",
    "password": "a-simple-password1"
}

# Post request for sending user details
POST  http://localhost:8080/api/post/form
Content-Type: application/json

{
    "name": "test"
}

POST http://localhost:8080/api/auth
Content-Type: application/json

{
    "username": "madhu-sujan",
    "password": "sujan"
}

GET http://localhost:8080/

GET http://localhost:8080/api/auth/status